openapi: 3.0.0
info:
  title: User Management API
  version: 1.0.0
paths:
  /accounts:
    get:
      summary: Get all accounts
      responses:
        '200':
          description: A list of user accounts
